### ISSUE TITLE
Incompatible with InvMove

### ISSUE THREAD

**Issue by Lenfant35** [Giant-Salted-Fish/Key-Binding-Patch#3] opened 2024-04-04 00:08 UTC
this mod is working very well. it has solved two different gun mods' reload key conflicts. but it is not compatible with the inventory move mod (https://www.curseforge.com/minecraft/mc-mods/invmove-forge/files/all?page=1&pageSize=20)

**Comment by al-wei** [comment] 2024-07-12 12:10
And 1.12.2

**Comment by Giant-Salted-Fish** [comment] 2024-11-17 11:42
Issue is confirmed when testing with [InvMove-1.12.2-0.4.6](https://www.curseforge.com/minecraft/mc-mods/invmove-forge/files/3023870/dependencies). Fixed in v1.3.3.1.

**Closed as completed** 2024-11-17 11:42 UTC
Labels: bug

**Comment by ihfuhgljclhflhc** [comment] 2025-11-18 00:31
Apparently no longer compatible

**Comment by Giant-Salted-Fish** [comment] 2025-11-19 16:48
> Apparently no longer compatible

Compatibility issue with InvMove is caused by the miss use of the Vanilla Keybinding API by InvMove. So later versions (from 1.3.3.3-beta) reverted corresponding compatibility fix. You can just stay on 1.3.3.2 version if you really want to use KBP with InvMove and cannot find other alternative. Newer version mainly optimized the mod config handling logic, which is not critical for usual gameplay.
