### ISSUE TITLE
Unable to use a combination of Shift and Ctrl / Non order specific controls?

### ISSUE THREAD

**Issue by Darkmega18** [Giant-Salted-Fish/Key-Binding-Patch#8] opened 2024-05-17 17:15 UTC
I use Shift + ctrl (sneak + sprint) to go prone/crawl or slide when using parcool. However the mod seems to inhibit my ability to set that control setting half of the time, resulting in "LShift+LShift" setting unless I push them at a very close time.

However it seems your controls are order sensitive?
At one point I managed to make it Lshift + ctrl by pressing them almost together. However then I could not sprint while holding ctrl, to then shift to slide _(same key as crawling, but while sprinting in motion)_ . But if I stop still and shifted and then ctrl'd it would prone.

Afterwards, I went into the options.txt myself and set it by hand and reloaded, but now as Lctrl + Lshift I NEED to sprint before I can prone because it requires ctrl to be pressed before shift.

Are you able to make the mod capable of processing them together in any order? where as long as the combination is eventually pressed together it will trigger when it becomes valid?
So I can sneak then crawl, but also sprint and slide, using the same combination. This combination is perfectly valid in minecraft 1.19.2 without any issues, but this seems to be a terrible issue of 1.20 versions where key binds are more pedantic than ever requiring this mod to exist in the first place.

**Comment by Giant-Salted-Fish** [comment] 2024-05-17 18:02
The tigger of the key binding is indeed order sensitive. For example, `Z+D` means that `Z` is the precondition for `D` hence need to be pressed first before pressing `D`. I did not expect such scenario before. But I think this can be resolved by adding the ability to shadow a key binding, which means you can set two key configurations to trigger the same functionality. By setting `Z+D` and `D+Z` together, its triggering should be order insensitive.

I am not sure if this could be implemented in the near future. And the co-existence of something like `Z` and `Z+D` could still cause unexpected confliction. The best practice so far is to set those key bindings with different key configuration.

**Comment by Giant-Salted-Fish** [comment] 2024-05-17 18:04
By the way, if setting a key configuration like `Lshif+Lctrl` is difficult, that usually indicates there exists some conflicts between `Key Binding Patch` and other mods that you have installed.

**Comment by Darkmega18** [comment] 2024-05-17 21:30
> By the way, if setting a key configuration like `Lshif+Lctrl` is difficult, that usually indicates there exists some conflicts between `Key Binding Patch` and other mods that you have installed.

Haiyahh. Controlling? it changes the control menu to be a bit easier to use with search function and conflict management etc. was the only other thing I had there related specifically to controls. I turned off modifier key fix which I had been using prior. so not sure what else.

I also had further issues related to setting Delete to turn on and off cheat mode for JEI and setting Shift+Del to hide JEI so I'd stop typing O somewhere in JEI's search and it turning itself off on me. The shift+Del button set up just didn't work at all.

it was a weird bug, cause sometimes typing O in search would trigger it and turn off JEI and sometimes it'd go just fine. Not sure what was happening there.



> The tigger of the key binding is indeed order sensitive. For example, `Z+D` means that `Z` is the precondition for `D` hence need to be pressed first before pressing `D`. I did not expect such scenario before. But I think this can be resolved by adding the ability to shadow a key binding, which means you can set two key configurations to trigger the same functionality. By setting `Z+D` and `D+Z` together, its triggering should be order insensitive.
> 
> I am not sure if this could be implemented in the near future. And the co-existence of something like `Z` and `Z+D` could still cause unexpected confliction. The best practice so far is to set those key bindings with different key configuration.

Can the mod be patched to trigger combination keys which become fulfilled together at that moment? So it'll trigger at the time when both shift and control end up being pressed rather than as a sequence? 

Most in game keys should preferably be fluid like that, unless you can add like a button or checkbox next to every key in the menu to allow them to be sequential _(must do Z -> D for Z+D to trigger. can't be D -> Z)_ or combinatory _(any time D and Z are combined together trigger the keybind as having been "pressed" then release it when the combination of held keys is no longer valid)_.

That way buttons that you definitely only want to trigger sometimes like menus or particularly special inputs can properly be walled off with a specific key combination, but fluid keys for like movement, casting and combat and such can be pushed in any combination to make them work fluidly.

**Comment by Darkmega18** [comment] 2024-05-18 11:38
what the hell. now I'm noticing I can't even sprint and attack? or sneak and mine at the same time? what the heck is going on? I just started playing a world properly after doing configs and I've run into 2 or 3 keybind issues with my general gameplay in the first minute.

**Comment by Giant-Salted-Fish** [comment] 2024-05-18 22:52
> what the hell. now I'm noticing I can't even sprint and attack? or sneak and mine at the same time? what the heck is going on? I just started playing a world properly after doing configs and I've run into 2 or 3 keybind issues with my general gameplay in the first minute.

That is probably caused by a bug someone else has reported. There exists some problem in handling the conflict context of the key bindings. And this is planned to be fixed in next update. (you can check if have some other key bindings that uses combination like `Lshift + Left Button`, and that could conflict with `Left Button` in current version).

> Can the mod be patched to trigger combination keys which become fulfilled together at that moment? So it'll trigger at the time when both shift and control end up being pressed rather than as a sequence?

Making it order sensitive is mainly for two reasons. The first is that this fits the intuition of the combination keys in other applications. For example, `Ctrl+F` to start search in an editor. It will not be triggered if you first press `F` then press `Ctrl`. Second reason is that this allows the multiple assignment of the same key. For example, if you assign `D` and `Z+D` to two different functionalities, in most cases that means these two functionalities should be triggered mutually. If you press `D` first and follows with `Z`, only the first functionality will be triggered. If you press `Z` first and follows `D`, only the second functionality will be triggered.

If sometimes you do need it to be order insensitive, then it can be treated as a special case where you have both `Z+D` and `D+Z` set for it. But this will not work in the other way around.

**Comment by Giant-Salted-Fish** [comment] 2024-05-19 01:15
> That is probably caused by a bug someone else has reported. There exists some problem in handling the conflict context of the key bindings. And this is planned to be fixed in next update. (you can check if have some other key bindings that uses combination like Lshift + Left Button, and that could conflict with Left Button in current version).

This problem has been fixed in v1.3.1.1 version. You can download the latest version and verify if the problem still exists.

**Comment by Darkmega18** [comment] 2024-05-19 09:06
> > That is probably caused by a bug someone else has reported. There exists some problem in handling the conflict context of the key bindings. And this is planned to be fixed in next update. (you can check if have some other key bindings that uses combination like Lshift + Left Button, and that could conflict with Left Button in current version).
> 
> This problem has been fixed in v1.3.1.1 version. You can download the latest version and verify if the problem still exists.

thank you, I'll give it a go.

**Comment by Giant-Salted-Fish** [comment] 2024-05-29 19:32
v1.3.2.1 has been released. It now supports the shadow key bindings which may settle your needs. You can upgrade and take a try.

**Closed as completed by Giant-Salted-Fish** 2024-05-29 19:32 UTC
